/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.presentacion.vista;

import itson.entidades.DTOs.TallerDTO;
import itson.presentacion.control.ControlInscripcion;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.util.List;

/**
 *
 * @author angel
 */
public class UI_ListaTalleres extends javax.swing.JPanel {

    private static final Color ITSON_AZUL = new Color(0, 87, 168);
    private static final Color BLANCO = Color.WHITE;
    private static final Color BORDE_TARJETA = new Color(180, 205, 235);

    private final ControlInscripcion control;
    private List<TallerDTO> talleresCache;
    private DefaultListModel<String> listModel;
    private JList<String> jListaTalleres;

    public UI_ListaTalleres(ControlInscripcion control) {
        this.control = control;
        initUI();
    }

    private void initUI() {
        setLayout(new BorderLayout());
        setBackground(BLANCO);
        setBorder(BorderFactory.createLineBorder(BORDE_TARJETA, 1, true));

        listModel = new DefaultListModel<>();
        jListaTalleres = new JList<>(listModel);
        jListaTalleres.setFont(new Font("Arial", Font.PLAIN, 15));
        jListaTalleres.setForeground(ITSON_AZUL);
        jListaTalleres.setBackground(BLANCO);
        jListaTalleres.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jListaTalleres.setSelectionBackground(new Color(210, 228, 248));
        jListaTalleres.setSelectionForeground(ITSON_AZUL);
        jListaTalleres.setFixedCellHeight(52);

        jListaTalleres.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> l, Object v, int i, boolean sel, boolean foc) {
                JLabel lbl = (JLabel) super.getListCellRendererComponent(l, v, i, sel, foc);
                lbl.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createMatteBorder(0, 0, 1, 0, BORDE_TARJETA),
                        new EmptyBorder(8, 18, 8, 8)));
                lbl.setFont(new Font("Arial", Font.PLAIN, 15));
                lbl.setForeground(ITSON_AZUL);
                if (!sel) {
                    lbl.setBackground(BLANCO);
                }
                return lbl;
            }
        });

        jListaTalleres.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jListaTalleres.getSelectedIndex() >= 0) {
                int idx = jListaTalleres.getSelectedIndex();
                if (talleresCache != null && idx < talleresCache.size()) {
                    control.seleccionarTaller(talleresCache.get(idx).getIdTaller());
                }
            }
        });

        JScrollPane scroll = new JScrollPane(jListaTalleres);
        scroll.setBorder(null);
        add(scroll);
    }

    public void cargarTalleres(List<TallerDTO> talleres) {
        this.talleresCache = talleres;
        listModel.clear();
        for (TallerDTO t : talleres) {
            listModel.addElement(t.getNombreCurso());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
